# general
cuda_index: 0
epoch: null

# saving model files
keep_last_models: 10
step_save_ckpt: 10000

# hyperparameters
batch_size: 256
learning_rate: 5.0e-4
lr_scheduler: CosineAnnealingWarmRestarts
lr_scheduler_kwargs:
  T_0: 5
  T_mult: 2
  eta_min: 1.0e-5
weight_decay: 0
d_model: 512
h: 8
ff: 2048
n_layers: 3
p_dropout: 0.1
seq_len: 256

# dataset
vocab_file: /home/dhchoi/projects/transformer_pytorch/kypark_dataset/bpe_dict/BPE_char_dict.json
vocab_start_token_id: 6
train_dataset_files:
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_en_tr_090.txt
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_ko_tr_090.txt
valid_dataset_files:
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_en_va_010.txt
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_ko_va_010.txt
shuffle_dataset_on_load: true