# general config
cuda_index: 0
epoch: null

# config for saving model files
keep_last_models: 10
step_save_ckpt: 10000

# config for model parameter
batch_size: 256
learning_rate: 0.0005
warm_up_epoch: 10
lr_gamma: 0.96
weight_decay: 1.0e-05
d_model: 512
h: 8
ff: 2048
n_layers: 3
p_dropout: 0.1
seq_len: 256

# config for dataset
vocab_file: /home/dhchoi/projects/transformer_pytorch/kypark_dataset/bpe_dict/BPE_char_dict.json
vocab_start_token_id: 6
train_dataset_files:
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_en_tr_090.txt
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_ko_tr_090.txt
valid_dataset_files:
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_en_va_010.txt
  - /home/dhchoi/projects/transformer_pytorch/kypark_dataset/encoded_corpus_files/BPE_char_ko_va_010.txt
shuffle_dataset_on_load: true